---
- name: Converge
  hosts: all
  vars:
    firewall_state: "{{ firewall_defaults.state | default('enabled') }}"
    firewall_enabled: "{{ firewall_defaults.enabled | default(true) }}"
    firewall_policy: "{{ firewall_defaults.policy | default('allow') }}"
    firewall_allowed_tcp_ports: "{{ firewall_rules.tcp_ports | default([]) }}"
    firewall_allowed_udp_ports: "{{ firewall_rules.udp_ports | default([]) }}"
    firewall_additional_rules: "{{ firewall_rules.custom | default([]) }}"
  tasks:
    - name: Include firewall role
      include_role:
        name: firewall