---
- import_playbook: instance.yml

- name: Configure PostgreSQL Database Servers
  hosts: postgres-*
  become: true
  strategy: free
  serial: 1
  vars:
    instance_role: database
    postgres_db: postgres
    postgres_user: postgres

  roles:
    - name: postgres/configure/primary
      when: (subdomain_instance_role | default('standalone')) == "master"
      tags: ["database"]

    - name: postgres/configure/standby
      when: (subdomain_instance_role | default('standalone')) == "standby"
      tags: ["database"]
  post_tasks:
    - name: Verify Primary using pg_stat_replication
      community.postgresql.postgresql_query:
        db: "{{ postgres_db }}"
        login_user: "{{ postgres_user }}"
        login_host: "127.0.0.1" 
        login_password: "{{ postgres_admin_password }}"
        query: "SELECT pid, usename, application_name, client_addr, state, sync_state FROM pg_stat_replication;"
      register: replication_status
      when: "'master' in hostvars[inventory_hostname].subdomain_instance_role"

