---
enable_firewall: false

# Firewall defaults
firewall_defaults:
  state: enabled
  log_dropped: true
  forward_policy: DROP

# Default firewall rules
firewall_base_rules:
  tcp_ports:
    - port: 22    
      comment: "SSH"
  udp_ports:
    - port: 53    
      comment: "DNS"
  custom: []
