---
firewall_defaults:
  state: enabled
  enabled: true

firewall_rules:
  tcp_ports:
    - port: 22    
      comment: "SSH"
    - port: 80    
      comment: "HTTP"
    - port: 443   
      comment: "HTTPS"
  udp_ports:
    - port: 53    
      comment: "DNS"
    - port: 123   
      comment: "NTP"
  custom: []
