---
# Base package configuration
enable_base_package: false
base_package_keys:
  apt: []
  yum: []

base_package_repos:
  yum:
    - name: grafana
      baseurl: https://rpm.grafana.com
      description: Grafana mono repository for Grafana ecosystem
      gpgcheck: yes
      gpgkey: https://rpm.grafana.com/gpg.key
      enabled: yes
  apt:
    - "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://apt.grafana.com stable main"

base_public_singing_keys:
  apt:
    - url: https://apt.grafana.com/gpg.key
      key: grafana.gpg
      state: present
  yum: []

base_packages:
  apt:
    - acl
    - ufw
    - gpg
    - auditd
    - lvm2
    - xfsprogs
    - e2fsprogs
    - parted
    - btrfs-progs
    - alloy
  yum:
    - acl
    - firewalld          # Tương đương ufw
    - gnupg2             # Tương đương gpg
    - audit              # Tương đương auditd
    - lvm2
    - xfsprogs
    - e2fsprogs
    - parted
    - alloy
    - chrony
