---
# Default storage configuration
enable_storage: true

storage_defaults:
  mount_options: defaults
  owner: root
  group: root
  mode: '0755'

# Default LVM configuration
lvm_defaults:
  pesize: "4M"
  vg_options: ""
