---
# Base groups
enable_users: true
base_groups:
  - name: guest
    gid: 3002

user_password_salt: "{{ linux_user_password_salt | default(lookup('env', 'USER_PASSWORD_SALT')) }}"

base_users:  
  - name: guest
    uid: 3002
    groups: ['guest']
    ssh_keys: []
