---
network_interfaces:
  - name: eth0  # Management network
    type: ethernet
    addresses:
      - "10.0.1.10/16"
    gateway4: "10.0.0.1"
    
  - name: eth1  # Kubernetes network
    type: ethernet
    addresses:
      - "172.16.1.10/16"
    routes:
      - to: 172.16.0.0/16
        via: 172.16.0.1

firewall_rules:
  input:
    - "-A INPUT -i eth1 -p tcp --dport 6443 -j ACCEPT"  # Kubernetes API
    - "-A INPUT -i eth1 -p tcp --dport 2379:2380 -j ACCEPT"  # etcd