# Mặc định cho Kafka KRaft role
kafka_minor: "4.0.0"
kafka_major: "2.13"
kafka_url: "https://downloads.apache.org/kafka/{{ kafka_minor }}/kafka_{{ kafka_major }}-{{ kafka_minor }}.tgz"
node_id: "{{ groups['kafka_nodes'].index(inventory_hostname) + 1 }}"
install_dir: "/opt/kafka"
data_dir: "/data/kafka"
config_dir: "{{ install_dir }}/config/kraft"

# Cấu hình KRaft
kafka_node_id: "{{ groups['kafka_nodes'].index(inventory_hostname) + 1 }}"
kafka_listeners:
  controller: "CONTROLLER://0.0.0.0:9093"
  broker: "PLAINTEXT://0.0.0.0:9092"
kafka_inter_broker_listener_name: "PLAINTEXT"
kafka_controller_listener_names: "CONTROLLER"
kafka_advertised_listeners: "PLAINTEXT://{{ ansible_default_ipv4.address }}:9092"

# Cấu hình topic
kafka_num_partitions: 3
kafka_default_replication_factor: 3
kafka_offsets_topic_replication_factor: 3
kafka_transaction_state_log_replication_factor: 3
kafka_transaction_state_log_min_isr: 2

# Tối ưu hóa hiệu năng
kafka_num_network_threads: 3
kafka_num_io_threads: 8
kafka_background_threads: 10
kafka_queued_max_requests: 500

# Cấu hình log retention
kafka_log_retention_hours: 168
kafka_log_retention_bytes: -1
kafka_log_segment_bytes: 1073741824
