---
- name: Set OS family facts
  set_fact:
    is_debian_based: "{{ ansible_os_family == 'Debian' }}"
    is_redhat_based: "{{ ansible_os_family == 'RedHat' }}"

- name: Configure timesyncd for Debian base
  include_tasks: timesyncd.yml
  when: is_debian_based

- name: Configure chrony for Redhat base
  include_tasks: chrony.yml
  when: is_redhat_based
