blackbox_exporter_arch: "{{ ansible_architecture | regex_replace('x86_64', 'amd64') | regex_replace('aarch64', 'arm64') }}"
blackbox_exporter_version: "0.25.0"
blackbox_exporter_url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ blackbox_exporter_arch }}.tar.gz"

blackbox_exporter_user: blackbox
blackbox_exporter_group: blackbox

blackbox_exporter_config_path: "/etc/blackbox_exporter/blackbox.yml"
blackbox_exporter_log_path: "/var/log/blackbox_exporter.log"

blackbox_default_timeout: "5s"
blackbox_chain_timeout: "30s"
blackbox_ip_protocol: "ip4"
