---
# Ubuntu specific configurations
ubuntu_enable_auto_updates: false
ubuntu_backports_enabled: false
ubuntu_universe_enabled: true
ubuntu_multiverse_enabled: false

# Package configuration
linux_add_packages_names: []
linux_remove_packages_names: []
linux_add_packages_cache_valid_time: 86400

# Repository configuration
linux_add_packages_keys: []
linux_add_packages_key_ids: []
linux_add_public_signing_keys: []
linux_add_packages_repositories: []
