---
firewall_default_rules:
  kafka:
    tcp_ports:
      - port: 9094
        scope: internal
        comment: "Kafka internal"
      - port: 9093
        scope: internal
        comment: "Kafka controller"
      - port: 9092
        comment: "Kafka external"
      - port: 9308
        comment: "Kafka exporter"
      - port: 2181
        comment: "Zookeeper client"
      - port: 2888
        comment: "Zookeeper Leader Election Follower Connection"
      - port: 3888
        comment: "Zookeeper Leader Election"
    custom: []
  redpanda:
    tcp_ports:
      - port: 8081
        comment: "Schema Registry"
      - port: 8082
        comment: "HTTP Proxy"
      - port: 9092
        comment: "Kafka API"
      - port: 9644
        comment: "Prometheus and Admin API"
      - port: 33145
        scope: internal
        comment: "Internal RPC"
    custom: []
  rabbitmq:
    tcp_ports:
      - port: 5672
        comment: "AMQP"
      - port: 15672
        comment: "Management UI"
      - port: 4369
        comment: "EPMD"
      - port: 25672
        scope: internal
        comment: "Cluster communication"
    custom: []
