---
- name: Mount BPF filesystem
  mount:
    path: /sys/fs/bpf
    src: bpf
    fstype: bpf
    opts: rw,nosuid,nodev,noexec,relatime
    state: mounted

- name: Ensure /usr/local/bin exists
  file:
    path: /usr/local/bin
    state: directory
    mode: '0755'

- name: Set Architecture string
  set_fact:
    cilium_arch: "{{ arch_mapping[ansible_architecture] | default('amd64') }}"

- name: Download Cilium CLI binary
  get_url:
    url: "https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-{{ cilium_arch }}.tar.gz"
    dest: "/tmp/cilium-linux-{{ cilium_arch }}.tar.gz"
  when: inventory_hostname in groups['masters']

- name: Extract Cilium CLI to /usr/local/bin
  unarchive:
    src: "/tmp/cilium-linux-{{ cilium_arch }}.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    mode: '0755'
  when: inventory_hostname in groups['masters']

- name: Setup Kubeconfig Link for Root
  file:
    path: /root/.kube
    state: directory
    mode: '0700'

- name: Create Symbolic Link to k0s Admin Config
  file:
    src: "/var/lib/k0s/pki/admin.conf"
    dest: "/root/.kube/config"
    state: link
    force: yes

- name: Install Cilium into Cluster
  ansible.builtin.shell: |
    /usr/local/bin/cilium install \
      --set kubeProxyReplacement=true \
      --set k8sServiceHost={{ ansible_host }} \
      --set k8sServicePort=6443 \
      --set ipam.operator.clusterPoolIPv4PodCIDRList="{{ k8s_pod_cidr }}" \
      --set operator.replicas=1
  when: inventory_hostname in groups['masters']
  register: install_out
  failed_when: 
    - install_out.rc != 0 
    - "'already installed' not in install_out.stderr"
    - "'still in use' not in install_out.stderr"  # Thêm dòng này để bắt lỗi "name still in use"
  changed_when: 
    - install_out.rc == 0
    - "'already installed' not in install_out.stdout"

- name: Enable full Hubble (Relay + UI)
  ansible.builtin.shell: |
    /usr/local/bin/cilium hubble enable --ui
  when: inventory_hostname in groups['masters']
  register: hubble_out
  failed_when: hubble_out.rc != 0 and 'already enabled' not in hubble_out.stdout
  changed_when: hubble_out.rc == 0
  when: install_out is succeeded or "'already installed' in install_out.stdout"

- name: Wait for Cilium status to be OK
  shell: "export KUBECONFIG={{ kubeconfig_path }} && /usr/local/bin/cilium status --wait"
  when: inventory_hostname in groups['masters']
  changed_when: false
