---
- name: RedHat/CentOS/Fedora | Install Wazuh repo
  yum_repository:
    name: wazuh_repo
    description: Wazuh repository
    baseurl: "{{ wazuh_repo.yum }}"
    gpgkey: "{{ wazuh_repo.gpg }}"
    gpgcheck: true
  changed_when: false

- name: RedHat/CentOS/Fedora | Install OpenJDK 1.8
  yum: name=java-1.8.0-openjdk state=present

- name: Linux CentOS/RedHat | Install wazuh-agent
  yum:
    name: wazuh-agent-{{ wazuh_agent_version }}
    state: present
    lock_timeout: '30'
  when:
    - ansible_os_family|lower == "redhat"
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager }}"
    WAZUH_AGENT_GROUP: "{{ wazuh_agent_group }}"

- name: lock version wazuh-agent
  community.general.yum_versionlock:
    name: wazuh-agent
    state: present
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

- name: install auditd
  yum:
    name: audit
    state: present

- name: enable auditd service
  service:
    name: auditd
    state: started
    enabled: yes
