- name: Restart elasticsearch
  block:
    - name: Restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted

    - name: Wait service to be ready
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 9200
        delay: 10
        timeout: 60

    - name: Wait for Cluster Health to be Green (Zero Downtime Safety)
      uri:
        url: "http://localhost:9200/_cluster/health"
        method: GET
      register: cluster_health
      until: cluster_health.json.status == "green"
      retries: 60
      delay: 15

- name: Restart nginx
  systemd:
    name: nginx
    state: restarted

- name: Daemon reload
  systemd:
    daemon_reload: yes
