---
- name: Set OS family facts
  set_fact:
    is_debian_based: "{{ ansible_os_family == 'Debian' }}"
    is_redhat_based: "{{ ansible_os_family == 'RedHat' }}"

- name: Configure firewall for Debian base
  include_tasks: ufw.yml
  when: is_debian_based

- name: Configure firewall for RedHat base
  include_tasks: firewald.yml
  when: is_redhat_based
