---
- name: Get current firewall state
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Reset ufw to default state
  ufw:
    state: reset
  when: 
    - firewall_enabled
    - "not 'Status: active' in ufw_status.stdout"

- name: Set firewall policy
  ufw:
    state: "{{ firewall_defaults.state }}"
    default: "{{ firewall_policy }}"
  when: 
    - firewall_enabled
    - "not 'Default: ' + firewall_policy in ufw_status.stdout"

- name: Configure allowed TCP ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: tcp
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_rules.tcp_ports | default([]) }}"
  when: 
    - firewall_enabled
    - firewall_rules.tcp_ports is defined
    - item.scope | default('public') == 'public'

- name: Configure Internal TCP ports (Cluster Only)
  ufw:
    rule: allow
    proto: tcp
    src: "{{ hostvars[item.0]['ansible_host'] }}"
    port: "{{ item.1.port | string }}"
    comment: "{{ item.1.comment | default('Internal Port') }} (Cluster Only)"
  with_nested:
    - "{{ ansible_play_hosts }}"
    - "{{ firewall_rules.tcp_ports | default([]) }}"
  when: 
    - firewall_enabled
    - firewall_rules.tcp_ports is defined
    - item.1.scope | default('public') == 'internal'

- name: Configure allowed UDP ports
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: udp
    comment: "{{ item.comment | default(omit) }}"
  loop: "{{ firewall_rules.udp_ports | default([]) }}"
  when:
    - firewall_enabled
    - firewall_rules.udp_ports is defined
    - item.scope | default('public') == 'public'

- name: Apply custom firewall rules
  ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    dst: "{{ item.dst | default(omit) }}"
  loop: "{{ firewall_rules.custom | default([]) }}"
  when:
    - firewall_enabled
    - firewall_rules.custom is defined

- name: Enable logging
  ufw:
    logging: on
  when: 
    - firewall_enabled
    - firewall_log_dropped_packets | default("true") | bool
