
firewall_default_rules:
  postgres-master:
    tcp_ports:
      - port: 5432
        comment: "Postgresql server"
    udp_ports: []
  postgres-standby:
    tcp_ports:
      - port: 5432
        comment: "Postgresql server"
    udp_ports: []
  scylladb:
    tcp_ports:
      - port: 7000
        comment: "Scylla Internode communication"
      - port: 7001
        comment: "Scylla TLS Internode communication"
      - port: 9160
        comment: "Scylla RPC port"
      - port: 9180
        comment: "Scylla monitor"
      - port: 9042
        comment: "Scylla CQL native port"
      - port: 9142
        comment: "Scylla TLS CQL native port"
      - port: 10000
        comment: "Scylla REST API"
      - port: 19042
        comment: "Scylla Native shard-aware transport port"
      - port: 19142
        comment: "Scylla TLS Native shard-aware transport port"
    udp_ports: []
  clickhouse:
    tcp_ports:
      - port: 9000
        comment: "Clickhouse non-TLS native port"
      - port: 9009
        scope: internal
        comment: "Clickhouse inter-link communication"
      - port: 9440
        comment: "Clickhouse TLS native port"
      - port: 9363
        comment: "Prometheus metrics"
      - port: 2181
        scope: internal
        comment: "Zookeeper client"
      - port: 2888
        scope: internal
        comment: "Zookeeper Leader Election Follower Connection"
      - port: 3888
        scope: internal
        comment: "Zookeeper Leader Election"
