---
- name: Ensure / has correct permissions
  file:
    path: /
    owner: root
    group: root
    mode: "0755"

- name: Ensure /var has correct permissions
  file:
    path: /var
    owner: root
    group: root
    mode: "0755"

- name: Ensure /var/log has correct permissions
  file:
    path: /var/log
    owner: root
    group: root
    mode: "0755"

- name: Configure logrotate global settings
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    mode: "0644"
    owner: root
    group: root
  notify: Restart logrotate

- name: Generate rsyslog.conf
  template:
    src: rsyslog.conf.j2
    dest: "/etc/rsyslog.conf"
  notify: Restart rsyslog

- name: Generate logrotate.d files
  template:
    src: logrotate-entry.conf.j2
    dest: "/etc/logrotate.d/{{ entry.name }}"
    mode: "0644"
    owner: root
    group: root
  vars:
    config: "{{ entry }}"
  loop: "{{ logrotate_entries }}"
  loop_control:
    loop_var: entry
  notify: Restart logrotate

- name: Generate rsyslog.d files
  template:
    src: rsyslog-entry.conf.j2
    dest: "/etc/rsyslog.d/{{ entry.rsyslog.id }}-{{ entry.rsyslog.program_name }}.conf"
    mode: '0644'
    owner: root
    group: root
  vars:
    program_name: "{{ entry.rsyslog.program_name }}"
    log_path: "{{ entry.path }}"
  when: entry.rsyslog is defined
  loop: "{{ logrotate_entries }}"
  loop_control:
    loop_var: entry
  notify: Restart rsyslog
