---
- name: Configure logrotate global settings
  template:
    src: "logrotate.conf.j2"
    dest: "/etc/logrotate.conf"
    mode: "0644"
    owner: root
    group: root
  notify: Restart logrotate

- name: Generate logrotate.d files
  template:
    src: log-entry.conf.j2
    dest: "/etc/logrotate.d/{{ entry.name }}"
    mode: "0644"
    owner: root
    group: root
  vars:
    config: "{{ entry }}"
  loop: "{{ logrotate_entries }}"
  loop_control:
    loop_var: entry
  notify: Restart logrotate

- name: Configure postgres logging
  template:
    src: rsyslog.conf.j2
    dest: "/etc/rsyslog.d/{{ entry.rsyslog.id }}-{{ entry.rsyslog.program_name }}.conf"
    mode: '0644'
    owner: root
    group: root
  vars:
    program_name: "{{ entry.rsyslog.program_name }}"
    log_path: "{{ entry.path }}"
  when: entry.rsyslog is defined
  loop: "{{ logrotate_entries }}"
  loop_control:
    loop_var: entry
  notify: Restart rsyslog
