---
network_interfaces: []
  # - name: eth0  # Public interface
  #   type: ethernet
  #   addresses:
  #     - "{{ ansible_host }}/24"
  #   gateway4: "{{ public_gateway }}"
  #   nameservers:
  #     addresses: ["8.8.8.8", "8.8.4.4"]

  # - name: br-data  # Data network bridge
  #   type: bridge
  #   copy: eth0
  #   addresses:
  #     - "192.168.0.1/16"
  #   bridge_ports: []
    
firewall_rules:
  nat: []
  #  - "-A POSTROUTING -s 192.168.0.0/16 -o eth0 -j MASQUERADE"
  forward: []
  #  - "-A FORWARD -i br-data -o eth0 -j ACCEPT"
  #  - "-A FORWARD -i eth0 -o br-data -m state --state RELATED,ESTABLISHED -j ACCEPT"
  input: []
  #  - "-A INPUT -i br-data -j ACCEPT"
