
role_users:
  gateway:
    - name: suricata
      uid: 2003
      groups: ['suricata']
      ssh_keys: []
    - name: matchbox
      uid: 2004
      groups: ['matchbox']
      ssh_keys: []
    - name: digirunner
      gid: 2005
      groups: ['digirunner']
      ssh_keys: []
    - name: blackbox
      gid: 2006
      groups: ['blackbox']
      ssh_keys: []

role_groups:
  gateway:
    - name: suricata
      gid: 2003
    - name: matchbox
      gid: 2004
    - name: digirunner
      gid: 2005
    - name: blackbox
      gid: 2006
