---
- name: Ensure Kafka version is 3.3 or greater
  fail:
    msg: "Kafka version {{ kafka_minor }} is older than 3.3. Minimum required version is 3.3."
  when: kafka_minor is version('3.3', '<')

- name: Set kafka_node_id fact for all kafka nodes
  ansible.builtin.set_fact:
    kafka_node_id: "{{ groups['kafka-nodes'].index(inventory_hostname) + 1 }}"
  delegate_to: "{{ inventory_hostname }}"
  when: inventory_hostname in groups['kafka-nodes']

- name: Debug controllers group and hostvars
  debug:
    msg: "{{ item }}: {{ hostvars[item]['kafka_node_id'] }} - {{ hostvars[item]['ansible_default_ipv4']['address'] }}"
  loop: "{{ groups['controllers'] }}"

- name: Initialize kafka_process_roles list
  set_fact:
    kafka_process_roles: []

- name: Set if in group controllers
  set_fact:
    kafka_process_roles: "{{ kafka_process_roles + ['controller'] }}"
  when: inventory_hostname in groups['controllers']

- name: Set if in group brokers
  set_fact:
    kafka_process_roles: "{{ kafka_process_roles + ['broker'] }}"
  when: inventory_hostname in groups['brokers']

- name: Initialize kafka_controller_quorum_voters list
  set_fact:
    kafka_controller_quorum_voters: []

- name: Build kafka_controller_quorum_voters list
  set_fact:
    kafka_controller_quorum_voters: "{{ kafka_controller_quorum_voters + [hostvars[item]['kafka_node_id'] | string + '@' + (hostvars[item]['full_hostname'] | default(hostvars[item]['inventory_hostname'])) + ':9093'] }}"
  loop: "{{ groups['controllers'] }}"

- name: Download Kafka binary
  get_url:
    url: "{{ kafka_url }}"
    dest: "/tmp/kafka.tgz"
    mode: '0644'

- name: Unarchive package
  unarchive:
    src: "/tmp/kafka.tgz"
    dest: "/tmp/"
    remote_src: yes
    owner: kafka
    group: kafka

- name: Check if source Kafka folder exists
  stat:
    path: /tmp/kafka_{{ kafka_major }}-{{ kafka_minor }}
  register: kafka_folder_stat
  when:
    - kafka_major is defined
    - kafka_minor is defined

- name: Rename Kafka folder to /opt/kafka
  command: mv /tmp/kafka_{{ kafka_major }}-{{ kafka_minor }} /opt/kafka
  args:
    creates: /opt/kafka
    removes: /tmp/kafka_{{ kafka_major }}-{{ kafka_minor }}
  become: yes
  when:
    - kafka_major is defined
    - kafka_minor is defined
    - kafka_folder_stat.stat.exists

- name: Create directories for Kafka
  file:
    path: "{{ item }}"
    state: directory
    owner: kafka
    group: kafka
  loop:
    - "{{ install_dir }}"
    - "{{ data_dir }}"
    - "{{ config_dir }}"

- name: Setup Mirrormaker 2
  block:
    - name: Render mm2.prperties
      template:
        src: mm2.properties.j2
        dest: "{{ config_dir }}/mm2.properties"
        owner: kafka
        group: kafka
        mode: '0644'
  when: kind == "mm2"

- name: Setup server  
  block:
    - name: Render server.properties for KRaft
      template:
        src: server.properties.j2
        dest: "{{ config_dir }}/server.properties"
        owner: kafka
        group: kafka
        mode: '0644'
      notify: Restart kafka
    
    - name: Generate cluster UUID (chạy trên node đầu tiên)
      command: "{{ install_dir }}/bin/kafka-storage.sh random-uuid"
      register: cluster_uuid
      run_once: true
      when:
        - inventory_hostname == groups['kafka-nodes'][0]
        - cluster_id is not defined
      become_user: kafka
    
    - name: Set cluster_id fact if generated
      set_fact:
        cluster_id: "{{ cluster_uuid.stdout }}"
      when:
        - inventory_hostname == groups['kafka-nodes'][0]
        - cluster_uuid.stdout is defined
      run_once: true
    
    - name: Distribute cluster UUID to all nodes
      copy:
        content: "{{ hostvars[groups['kafka-nodes'][0]]['cluster_id'] }}"
        dest: "/tmp/cluster_id.txt"
        owner: kafka
        group: kafka
      when: inventory_hostname != groups['kafka-nodes'][0]
    
    - name: Format storage for KRaft
      command: "{{ install_dir }}/bin/kafka-storage.sh format -t {{ hostvars[groups['kafka-nodes'][0]]['cluster_uuid']['stdout'] | default(cluster_id) }} -c {{ config_dir }}/server.properties"
      become_user: kafka
      args:
        creates: "{{ data_dir }}/meta.properties"
    
    - name: Create systemd service for Kafka
      copy:
        content: |
          [Unit]
          Description=Apache Kafka KRaft
          After=network.target
    
          [Service]
          Type=simple
          User=kafka
          ExecStart={{ install_dir }}/bin/kafka-server-start.sh {{ config_dir }}/server.properties
          ExecStop={{ install_dir }}/bin/kafka-server-stop.sh
          Restart=always
    
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/kafka.service
        mode: '0644'
      notify: Daemon reload
    
    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes
    
    - name: Start and enable Kafka service
      systemd:
        name: kafka
        enabled: yes
        state: started
  when: kind == "server"
