---
- name: Configure Citus extension
  postgresql_ext:
    name: citus
    db: postgres
    state: present
    login_user: postgres
  become: true
  become_user: postgres

- name: Set Citus configuration parameters
  postgresql_set:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    db: postgres
    login_user: postgres
  loop: "{{ citus_config_params }}"
  become: true
  become_user: postgres
  notify: restart postgresql

