---
- import_playbook: ../boilerplate.yml

- name: Configure Gateway Instance
  hosts: gateway-*
  become: true
  vars:
    instance_role: gateway

  pre_tasks:
    - name: Include role specific variables
      include_vars:
        dir: "{{ item }}"
        ignore_unknown_extensions: true
        extensions: ['yml', 'yaml']
      loop:
        - "../../group_vars/all"
        - "../../group_vars/gateway"
      tags: ["always"]

    - name: Check if host_vars directory exists
      ansible.builtin.stat:
        path: "../../host_vars/{{ inventory_hostname }}"
      register: host_vars_dir
      tags: ["always"]

    - name: Include host specific variables
      include_vars:
        dir: "../../host_vars/{{ inventory_hostname }}"
        ignore_unknown_extensions: true
        extensions: ['yml', 'yaml']
      when: host_vars_dir.stat.exists
      tags: ["always"]
  roles:
    # @NOTE: setup prometheus
    - role: prometheus
      when: (instance_role == 'gateway') and (lighthouse_enabled | default(false))
      tags: ["monitor"]

    # @NOTE: setup blackbox
    - role: exporters/blackbox
      when: (instance_role == 'gateway') and (lighthouse_enabled | default(false))
      tags: ["monitor"]

    # @NOTE: setup suricata
    - role: suricata
      vars:
        suricata_home_net: >-
          {{
            ([ansible_default_ipv4.network + '/' + (ansible_default_ipv4.netmask | ansible.utils.ipaddr('prefix') | string)]) +
            (network_interfaces | selectattr('type', 'equalto', 'bridge') | map(attribute='addresses') | flatten | list)
          }}
        suricata_interfaces: >-
          {{ network_interfaces }}
      when: (instance_role == 'gateway') and (suricate_enabled | default(false))
      tags: ["security", "ids"]

    # @NOTE: setup digirunner
    - role: digirunner
      when: (instance_role == 'gateway') and (digirunner_enabled | default(false))
      tags: ["gateway"]

    # @NOTE: setup bind
    - role: bind
      vars:
        internal_zones: "{{ bind_configs.zones | default([]) }}"
        internal_subnets: "{{ bind_configs.subnets | default([]) }}"
        internet_dns_resolvers: "{{ bind_configs.nameservers | default([]) }}"
      when: (instance_role == 'gateway') and (dns_enabled | default(false))
      tags: ["network", "dns"]

    # @NOTE: setup bind exporter
    - role: exporters/bind
      when: (instance_role == 'gateway') and (dns_enabled | default(false))
      tags: ["network", "dns"]

    # @NOTE: setup matchbox
    - role: matchbox
      when: (instance_role == 'gateway') and (matchbox_enabled | default(false))
      tags: ["network", "matchbox"]

    # @NOTE: setup tftp
    - role: tftp
      vars:
        tftp_root: "{{ tftp_root_dir | default('/srv/tftp') }}"
        boot_menu_items: "{{ pxe_menu_items | default([]) }}"
      when: (instance_role == 'gateway') and (tftp_enabled | default(false))
      tags: ["network", "tftp"]

    # @NOTE: Setup ipvs to group tftp cluster
    - role: loadbalancer/ipvs
      vars:
        ipvs_services:
          - name: tftp
            address: "{{ gateway_virtual_ip }}"
            port: 69
            protocol: udp
            scheduler: wrr
            real_servers: "{{ gateway_real_servers }}"
      when: instance_role == 'gateway' and gateway_virtual_ip is defined and gateway_real_servers is defined
      tags: ["network", "ipvs"]

    # @TODO: setup custom scripts to link between dhcpd, tftp and matchbox
    
    # @TODO: setup custom script to link between dhcpd and suricata

    # @TODO: thinking about using tftp on top of nfs/drbd and use ipvs to configure alias ip for fetching data
