---
- import_playbook: ../boilerplate.yml

- name: Configure RabbitMQ Instance
  hosts: all
  become: true
  vars:
    instance_role: eventdriver
    subdomain_instance_role: rabbitmq

  pre_tasks:
    - name: Include role specific variables
      include_vars:
        dir: "{{ item }}"
        ignore_unknown_extensions: true
        extensions: ['yml', 'yaml']
      loop:
        - "../../group_vars/all"
        - "../../group_vars/{{ instance_role }}"
      tags: ["always"]

    - name: Check if host_vars directory exists
      ansible.builtin.stat:
        path: "../../host_vars/{{ inventory_hostname }}"
      register: host_vars_dir
      tags: ["always"]

    - name: Include host specific variables
      include_vars:
        dir: "../../host_vars/{{ inventory_hostname }}"
        ignore_unknown_extensions: true
        extensions: ['yml', 'yaml']
      when: host_vars_dir.stat.exists
      tags: ["always"]

  roles:
    - role: rabbitmq
      vars:
        erlang_cookie: "GlAKxO1hcErroQhycsKIiiMrXuSWmNsAGaJkYNW0"
      tags: ["rabbitmq"]
